window.FIREBASE_CONFIG={apiKey:"AIzaSyC_Y-V5OIG61B7x7H54RNVwPL3vBeeyvtM",authDomain:"french-da79a.firebaseapp.com",databaseURL:"https://french-da79a-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"french-da79a",appId:"1:534791612002:web:e9a9a990d351ced860133b"};
window.AN2_ADMIN_USERNAME='boikot5225';
window.AN2_FIREBASE_FUNCTIONS_REGION='asia-southeast1';
window.AN2_AUTH_BOOTSTRAP='reader-auth-v71.7';
(function(){
const c=window.FIREBASE_CONFIG,K='an2_firebase_rest_session_v1',apps=[],listeners=new Set(),base=new URL('.',document.currentScript?.src||location.href);
let s;try{s=JSON.parse(localStorage.getItem(K)||'null');if(!s?.uid||!s?.idToken)s=null;}catch(_){s=null;}let user=null;
const err=(x,f)=>{const m=String(x?.error?.message||x?.message||f||'auth/network-request-failed'),q={EMAIL_NOT_FOUND:'auth/user-not-found',INVALID_PASSWORD:'auth/wrong-password',INVALID_LOGIN_CREDENTIALS:'auth/invalid-credential',EMAIL_EXISTS:'auth/email-already-in-use',WEAK_PASSWORD:'auth/weak-password',OPERATION_NOT_ALLOWED:'auth/operation-not-allowed',CONFIGURATION_NOT_FOUND:'auth/configuration-not-found',INVALID_EMAIL:'auth/invalid-email'},e=new Error(m);e.code=q[m]||f||'auth/network-request-failed';return e;};
const save=()=>{try{s?localStorage.setItem(K,JSON.stringify(s)):localStorage.removeItem(K);}catch(_){}};
const emit=()=>listeners.forEach(f=>{try{f(user)}catch(_){}});
const makeUser=x=>x?{uid:x.uid,email:x.email||'',async getIdToken(force){if(force&&x.refreshToken){const b=new URLSearchParams({grant_type:'refresh_token',refresh_token:x.refreshToken}),r=await fetch('https://securetoken.googleapis.com/v1/token?key='+encodeURIComponent(c.apiKey),{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:b}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw err(j);x.idToken=j.id_token||x.idToken;x.refreshToken=j.refresh_token||x.refreshToken;save()}return x.idToken}}:null;
user=makeUser(s);
async function sign(up,email,password){const r=await fetch('https://identitytoolkit.googleapis.com/v1/'+(up?'accounts:signUp':'accounts:signInWithPassword')+'?key='+encodeURIComponent(c.apiKey),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:String(email||'').trim(),password:String(password||''),returnSecureToken:true})}),j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw err(j);s={uid:j.localId,email:j.email||email||'',idToken:j.idToken,refreshToken:j.refreshToken||''};user=makeUser(s);save();emit();return{user};}
const state={Auth:{Persistence:{LOCAL:'LOCAL'}},get currentUser(){return user},setPersistence:async()=>{},onAuthStateChanged(f){listeners.add(f);Promise.resolve().then(()=>{try{f(user)}catch(_){}});return()=>listeners.delete(f)},signInWithEmailAndPassword:(e,p)=>sign(false,e,p),createUserWithEmailAndPassword:(e,p)=>sign(true,e,p),signOut:async()=>{s=null;user=null;save();emit()}};const auth=()=>state;auth.Auth=state.Auth;
function ref(path=''){const p=String(path).replace(/^\/+|\/+$/g,''),go=async(m,v)=>{const t=user?await user.getIdToken(false):'',u=c.databaseURL.replace(/\/+$/,'')+(p?'/'+p:'')+'.json'+(t?'?auth='+encodeURIComponent(t):''),r=await fetch(u,{method:m,headers:{'Content-Type':'application/json'},body:v===undefined?undefined:JSON.stringify(v)}),j=m==='DELETE'?null:await r.json().catch(()=>null);if(!r.ok||j?.error)throw err(j,'permission-denied');return j};return{async get(){const v=await go('GET');return{exists:()=>v!==null&&v!==undefined,val:()=>v}},set:v=>go('PUT',v),update:v=>go('PATCH',v),remove:()=>go('DELETE')}}
const fb={apps,initializeApp(){if(!apps.length)apps.push({name:'[DEFAULT]'});return apps[0]},app(){if(!apps.length)apps.push({name:'[DEFAULT]'});return apps[0]},auth,database:()=>({ref}),__an2RestFallback:true};
const install=()=>{window.firebase=fb};install();window.__AN2_FALLBACK_FIREBASE=fb;window.an2FirebaseSdkReady=Promise.resolve(true);
window.addEventListener('DOMContentLoaded',()=>setTimeout(async()=>{try{const m=await import(new URL('supabase.js',base).href);if(!m.isSupabaseReady()){install();m.initSupabase();}console.warn('[an2 auth ready]',m.isSupabaseReady?.())}catch(e){console.error('[an2 auth repair]',e)}},0),{once:true});
})();
