package smartbook.pinyin

import java.io.InputStream
import java.util.zip.GZIPInputStream

/** Minimal dictionary contract needed by segmentation and inline pinyin. */
interface ChineseLexicon {
    val maxWordLength: Int
    fun contains(word: String): Boolean
    fun pinyin(word: String): String?
}

class MapChineseLexicon private constructor(
    private val readings: Map<String, String>,
    override val maxWordLength: Int,
) : ChineseLexicon {

    override fun contains(word: String): Boolean = readings.containsKey(word)

    override fun pinyin(word: String): String? = readings[word]

    companion object {
        fun from(entries: Map<String, String>): MapChineseLexicon {
            val cleaned = LinkedHashMap<String, String>(entries.size)
            var maxLength = 1
            for ((rawWord, rawPinyin) in entries) {
                val word = rawWord.trim()
                val pinyin = rawPinyin.trim()
                if (word.isEmpty() || pinyin.isEmpty()) continue
                cleaned[word] = pinyin
                maxLength = maxOf(maxLength, word.codePointCount(0, word.length))
            }
            return MapChineseLexicon(cleaned, maxLength)
        }

        /** Reads the compact gzip/TSV asset generated by tools/build_lexicon.py. */
        fun fromTsv(input: InputStream): MapChineseLexicon {
            val map = LinkedHashMap<String, String>(131_072)
            input.bufferedReader(Charsets.UTF_8).useLines { lines ->
                lines.forEach { line ->
                    if (line.isBlank() || line.startsWith('#')) return@forEach
                    val tab = line.indexOf('\t')
                    if (tab <= 0 || tab >= line.lastIndex) return@forEach
                    val word = unescape(line.substring(0, tab))
                    val pinyin = unescape(line.substring(tab + 1))
                    if (word.isNotBlank() && pinyin.isNotBlank()) map[word] = pinyin
                }
            }
            return from(map)
        }

        fun fromGzipTsv(input: InputStream): MapChineseLexicon =
            GZIPInputStream(input.buffered()).use(::fromTsv)

        private fun unescape(value: String): String = buildString(value.length) {
            var i = 0
            while (i < value.length) {
                val ch = value[i]
                if (ch == '\\' && i + 1 < value.length) {
                    when (value[i + 1]) {
                        't' -> append('\t')
                        'n' -> append('\n')
                        'r' -> append('\r')
                        '\\' -> append('\\')
                        else -> {
                            append(ch)
                            append(value[i + 1])
                        }
                    }
                    i += 2
                } else {
                    append(ch)
                    i++
                }
            }
        }
    }
}
